name: "\U0001F680 New feature proposal"
description: Propose a new feature to be added to Big Calendar
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Clear and concise description of the problem
      description: As a developer using Big Calendar I want [goal / wish] so that [benefit]
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: 'In module [xy] we could provide following implementation...'
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Would you like to open a PR for this feature?
      description: Before starting to work on PR it is recommended to get maintainers approval. The fastest, and most appreciated way to have feature included is to create a pull request with working, tested code and we will help get it merged. Don't be scared to open a pull request that isn't completed and ask for input. We're happy to give direction!
      options:
        - label: I'm willing to open a PR
          required: false