// options for commonjs rollup plugin
export default {
  exclude: ['node_modules/process-es6/**'],
  include: [
    'node_modules/create-react-class/**',
    'node_modules/fbjs/**',
    'node_modules/object-assign/**',
    'node_modules/prop-types/**',
    'node_modules/classnames/**',
    'node_modules/object.assign/**',
    'node_modules/object.values/**',
    'node_modules/object-keys/**',
    'node_modules/function-bind/**',
    'node_modules/foreach/**',
    'node_modules/es-abstract/**',
    'node_modules/has/**',
    'node_modules/is-callable/**',
    'node_modules/is-regex/**',
    'node_modules/is-date-object/**',
    'node_modules/is-plain-object/**',
    'node_modules/is-symbol/**',
    'node_modules/es-to-primitive/**',
    'node_modules/define-properties/**',
    'node_modules/consolidated-events/**',
    'node_modules/is-touch-device/**',
  ],
}
