name: Test

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install Dependencies
        run: yarn install

      - name: Unit Test & Linting
        run: yarn test

      - name: Build
        run: yarn build
